


SELECT
    t1.dtRef,
    t1.idCliente,
    t1.idadeDias, 
    t1.qtdeAtivacaoVida, 
    t1.qtdeAtivacaoVidaD7, 
    t1.qtdAtivacaoVidaD14, 
    t1.qtdAtivacaoVidaD28, 
    t1.qtdAtivacaoVidaD56, 
    t1.qtdeTransacaoVida, 
    t1.qtdeTransacaoVidaD7, 
    t1.qtdTransacaoVidaD14, 
    t1.qtdTransacaoVidaD28, 
    t1.qtdTransacaoVidaD56, 
    t1.saldoVida, 
    t1.saldoVidaD7, 
    t1.saldoVidaD14, 
    t1.saldoVidaD28, 
    t1.saldoVidaD56, 
    t1.qtdePontosPosVida, 
    t1.qtdePontosPosVidaD7, 
    t1.qtdePontosPosVidaD14, 
    t1.qtdePontosPosVidaD28, 
    t1.qtdePontosPosVidaD56, 
    t1.qtdePontosNegVida, 
    t1.qtdePontosVidaD7, 
    t1.qtdePontosNegVidaD14, 
    t1.qtdePontosNegVidaD28, 
    t1.qtdePontosNegVidaD56, 
    t1.qtdeTransacaoManha, 
    t1.qtdeTransacaoTarde, 
    t1.qtdeTransacaoNoite, 
    t1.pctTransacaoManha, 
    t1.pctTransacaoTarde, 
    t1.pctTransacaoNoite, 
    t1.qtdeTransacaoDiaVida, 
    t1.qtdeTransacaoDiaD7, 
    t1.qtdeTransacaoDia14, 
    t1.qtdeTransacaoDia28, 
    t1.qtdeTransacaoDia56, 
    t1.pctAtivacaoMAU, 
    t1.qtdeHorasVida, 
    t1.qtdeHorasD7, 
    t1.qtdeHorasD14, 
    t1.qtdeHorasD28, 
    t1.qtdeHorasD56, 
    t1.avgIntervaloDiasVida, 
    t1.avgIntervaloDiasD28, 
    t1.qteChatMessage, 
    t1.qteAirflowLover, 
    t1.qteRLover, 
    t1.qteResgatarPonei, 
    t1.qteListadepresenca, 
    t1.qtePresencaStreak, 
    t1.qteTrocaStreamElements, 
    t1.qteReembolsoStreamElements, 
    t1.qtdeRPG, 
    t1.qtdeChurnModel,
    t2.descLifeCycleAtual, 
    t2.descLifeCycleD28, 
    t2.pctFiel, 
    t2.pctZumbi, 
    t2.pctDesencantada, 
    t2.pctCurioso, 
    t2.pctTurista, 
    t2.pctReconquistada, 
    t2.pctReborn, 
    t2.avgFreqGrupo, 
    t2.ratioFreqGrupo,
    t3.qtedCursosCompletos, 
    t3.qtedCursosIncompletos, 
    t3.carreira, 
    t3.coletaDados2024, 
    t3.dsDatabricks2024, 
    t3.dsPontos2024, 
    t3.estatistica2024, 
    t3.estatistica2025, 
    t3.github2024, 
    t3.github2025, 
    t3.iaCanal2025, 
    t3.lagoMago2024, 
    t3.loyaltyPredict2025, 
    t3.machineLearning2025, 
    t3.matchmakingTramparDeCasa2024, 
    t3.ml2024, 
    t3.mlflow2025, 
    t3.nekt2025, 
    t3.pandas2024, 
    t3.pandas2025, 
    t3.python2024, 
    t3.python2025, 
    t3.speedF1, 
    t3.sql2020, 
    t3.sql2025, 
    t3.streamlit2025, 
    t3.tramparLakehouse2024, 
    t3.tseAnalytics2024, 
    t3.qtdeDiasUltimaInteracao
FROM
    fs_transacional t1

LEFT JOIN
    fs_life_cycle t2
ON t1.idCliente = t2.IdCliente
    AND t1.dtRef = t2.dtRef

LEFT JOIN
    fs_education t3
ON t1.idCliente = t3.IdCliente
    AND t1.dtRef = t3.dtRef

WHERE t1.dtRef = (SELECT MAX(dtRef) FROM fs_transacional)

